### ISSUE TITLE
save translation-file in a different directory

### ISSUE THREAD

**Issue by pixelriot** [Frixuu/GodotXliff#1]
I would like to have the generated .translation-files not be in the .import directory but instead, next to my xliff-files. Is that somehow possible to achieve?

Thanks for the great work.

**Comment by Frixuu** [comment]
Hey, I've pushed [a change to a separate branch](https://github.com/Frixuu/GodotXliff/tree/test-import-alongside-original) that may help with this. The setting to control it has to be per-project (`addons/xliff/generated_file_location`) rather than per-file though.

Let me know if it works for you!

**Comment by pixelriot** [comment]
Works like a charm :)

Thank you very much.

**Comment by pixelriot** [comment]
... thus closing this ssue.
